# Generated by Django 2.0.3 on 2018-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('iscup', models.BooleanField()),
            ],
        ),
    ]
