# Generated by Django 2.0.3 on 2018-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0002_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='iscup',
        ),
        migrations.AddField(
            model_name='league',
            name='is_cup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='league',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
