# Generated by Django 2.0.3 on 2018-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0003_auto_20180309_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
