# Generated by Django 2.0.3 on 2018-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0004_auto_20180309_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
