# Generated by Django 2.0.3 on 2018-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0006_auto_20180309_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
