# Generated by Django 2.0.3 on 2018-03-14 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0008_auto_20180309_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_name', models.TextField()),
                ('bet_short_name', models.CharField(max_length=128)),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_choice', models.CharField(max_length=128)),
                ('bet_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tippspiel.BetGroup')),
            ],
        ),
        migrations.CreateModel(
            name='MatchBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1.0)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tippspiel.BetType')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tipp',
            name='score_home',
        ),
        migrations.RemoveField(
            model_name='tipp',
            name='score_visitor',
        ),
        migrations.AddField(
            model_name='tipp',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='tipp',
            name='bet_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tipp',
            name='state',
            field=models.CharField(default='In Game', max_length=128),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_visitor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipp',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='matchbet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tippspiel.Match'),
        ),
        migrations.AddField(
            model_name='tipp',
            name='bet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tippspiel.BetType'),
            preserve_default=False,
        ),
    ]
