# Generated by Django 2.0.3 on 2018-03-16 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0009_auto_20180314_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipp',
            name='bet_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='tipp',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
