# Generated by Django 2.0.3 on 2018-03-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0010_auto_20180316_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettype',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
