# Generated by Django 2.0.3 on 2018-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0011_bettype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='xmlsoccer_matchid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
