# Generated by Django 2.0.3 on 2018-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0012_auto_20180320_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettype',
            name='max_value',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='bettype',
            name='min_value',
            field=models.DecimalField(decimal_places=8, default=1e-05, max_digits=16),
        ),
        migrations.AddField(
            model_name='matchbet',
            name='max_value',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='matchbet',
            name='min_value',
            field=models.DecimalField(decimal_places=8, default=1e-05, max_digits=16),
        ),
    ]
